config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper
  devise_for :users

  concern :votable do
    post 'up' => 'votes#up'
    post 'down' => 'votes#down'
  end

  resources :questions do
    resources :answers, only: [:create, :edit, :update]
    resources :comments, only: [:new, :create]
    concerns :votable
  end

  resources :answers, only: [:edit, :update] do
    resources :comments, only: [:new, :create]
    concerns :votable
  end

  resources :tags, only: [:index]

  resources :search, only: [:index]

  root 'questions#index'
  get 'tagged' => 'questions#tagged', :as => 'tagged'

  namespace 'api', defaults: {format: 'json'} do
    namespace 'v1' do
      resource :profiles do
        get :me, on: :collection
        get :index, on: :collection
      end

      resources :questions, only: [:index, :show] do
      end
    end
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers
  has_many :comments, as: :commentable
  has_many :attachments, as: :attachmentable

  acts_as_taggable
  acts_as_votable
  is_impressionable

  accepts_nested_attributes_for :attachments, allow_destroy: true, reject_if: :all_blank

  validates :title, presence: true, uniqueness: true, length: {
      within: 10..40,
      too_short: 'Title must be more than 10 characters',
      too_long: 'Title cannot be more than 40 characters'
  }

  validates :body, presence: true, length: {
      within: 50..5000,
      too_short: 'Question must be more than 50 characters',
      too_long: 'Question cannot be more than 5000 characters'
  }
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  respond_to :json

  def index
    respond_with collection, each_serializer: QuestionsListSerializer, meta: {timestamp: collection.last.created_at}
  end
end

app/controllers/questions_controller.rb
class QuestionsController < InheritedResources::Base
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]
  before_action :build_answer, only: :show
  before_action :build_attachments, only: :new
  # before_action :question_belongs_to_current_user, only: [:edit, :update]
  impressionist actions: [:show], unique: [:session_hash]

  load_and_authorize_resource

  layout 'application', only: [:index, :edit, :new, :tagged]

  def tagged
    if params[:tag].present?
      @questions = Question.tagged_with(params[:tag])
    else
      redirect_to tags_path
    end
  end

  protected

  def create_resource(object)
    object.user = current_user
    object.attachments.each do |attachment|
      attachment.user = current_user
    end
    super
  end

  # TODO: switch to cancan.
  def question_belongs_to_current_user
    unless current_user == resource.user
      flash[:notice] = 'This is not your question.'
      redirect_to root_path
    end
  end

  def build_attachments
    build_resource.attachments.build
  end

  def build_answer
    @answer = resource.answers.build if user_signed_in?
    @answer.attachments.build if user_signed_in?
  end

  def question_params
    params.require(:question).permit(:tag_list, :title, :body, attachments_attributes: [:id, :_destroy, :attachment])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/questions/edit.html.slim
= bootstrap_nested_form_for @question do |f|
  = f.text_field :title, autofocus: true
  = f.text_area :body, label: 'Question'
  = f.text_field :tag_list, class: 'tagsinput'
  = f.fields_for :attachments do |file|
    = link_to file.object.attachment.file.filename, file.object.attachment.url unless file.object.new_record?
    = file.file_field :attachment, hide_label: true if file.object.new_record?
    = file.link_to_remove ' - remove'
  = f.link_to_add 'add', :attachments
  | <br>
  = f.primary 'Edit question'

app/views/questions/index.html.slim
.questions
  -for q in @questions do
    .well
      .row
        .col-md-1.votes.counts
          .item-count #{q.get_upvotes.size - q.get_downvotes.size}
          p.small votes
        .col-md-1.answers.counts
          .item-count #{q.answers.count}
          p.small answers
        .col-md-1.views.counts
          .item-count #{q.impressionist_count}
          p.small views
        .col-md-9
          .question-title #{link_to q.title, q}
          span.small #{q.user.name} at #{q.created_at.strftime("%H:%M")}
          .tags
            -q.tags.any?
              - q.tags.each do |tag|
                span.label.label-default = link_to tag.name, tagged_path(tag: tag.name)

app/views/questions/new.html.slim
= bootstrap_nested_form_for @question do |f|
  = f.text_field :title, autofocus: true
  = f.text_area :body, label: 'Question'
  = f.text_field :tag_list, class: 'tagsinput'
  = f.fields_for :attachments do |file|
    = file.file_field :attachment
    = file.link_to_remove 'remove'
  = f.link_to_add 'add', :attachments
  = f.primary 'Ask question'

app/views/questions/show.html.slim
.question.entry data={question_id: "#{@question.id}"}
  h2= @question.title
  .meta
    span.glyphicon.glyphicon-time= @question.created_at.strftime("%H:%M")
    span.glyphicon.glyphicon-user= @question.user.name
    span.pull-right.glyphicon.glyphicon-comment= @question.answers.count

  .vote
    .votecount = @question.get_upvotes.size - @question.get_downvotes.size
    = link_to 'Vote up', question_up_path(@question), remote: true, method: :post, class: 'up' if user_signed_in?
    = link_to 'Vote down', question_down_path(@question), remote: true, method: :post, class: 'down' if user_signed_in?
  - if can? :update, @question
    = link_to 'Edit question', edit_question_path(@question)

  p= @question.body

  .well
    .row
      .tags
        h5 Tags:
        - @question.tags.any?
          - for tag in @question.tags do
            = link_to tag.name, tagged_path(tag: tag.name)


  - if @question.attachments[0].respond_to?('attachment')
    - for attachment in @question.attachments do
      - if attachment.attachment.file.respond_to?('filename')
        = link_to attachment.attachment.file.filename, attachment.attachment.url
  br
  .pull-right
    = link_to 'Comment question', new_question_comment_path(@question), remote: true, id: 'question-comment'
  ul.chat
    .question-comments
      - if @question.comments
        - for c in @question.comments do
          li.right-chat.clearfix
            span.chat-img.pull-right
              = gravatar_image_tag(c.user.email, alt: c.user.name, class: 'img-circle', size: 50, gravatar: { size: 50 })
            .chat-body.clearfix
              .header
                strong.pull-right.primary-font #{c.user.name}
                small.text-muted
                  span.glyphicon.glyphicon-time
                  | #{time_ago_in_words c.created_at} ago
              p = c.body
  .question-comment-form
  .answers
    =render 'answers/answers', question: resource


.answer-errors
- if can? :create, @answer
  = bootstrap_nested_form_for [@question, @answer], remote: true do |f|
    = f.text_area :body, hide_label: true
    = f.fields_for :attachments, remote: true do |file|
      = file.file_field :attachment
      = file.link_to_remove 'remove'

    = f.primary   'Give answer'
- else
  p
    | You need to sign in or sign up before commenting.

app/views/questions/tagged.html.slim
.questions
  .row-fluid
    -for q in @questions do
      .row
        .counts
          .col-md-1.votes
            .item-count 0
            p.small votes
          .col-md-1.answers
            .item-count #{q.answers.count}
            p.small answers
          .col-md-1.views
            .item-count 0
            p.small views
        .col-md-9
          .question-title #{link_to q.title, q}
          span.small #{q.user.name} at #{q.created_at.strftime("%H:%M")}
          .tags
            -q.tags.any?
              - q.tags.each do |tag|
                span.label.label-default = link_to tag.name, tagged_url(tag: tag.name)