config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper
  devise_for :users

  concern :votable do
    post 'up' => 'votes#up'
    post 'down' => 'votes#down'
  end

  resources :questions do
    resources :answers, only: [:create, :edit, :update]
    resources :comments, only: [:new, :create]
    concerns :votable
  end

  resources :answers, only: [:edit, :update] do
    resources :comments, only: [:new, :create]
    concerns :votable
  end

  resources :tags, only: [:index]

  resources :search, only: [:index]

  root 'questions#index'
  get 'tagged' => 'questions#tagged', :as => 'tagged'

  namespace 'api', defaults: {format: 'json'} do
    namespace 'v1' do
      resource :profiles do
        get :me, on: :collection
        get :index, on: :collection
      end

      resources :questions, only: [:index, :show] do
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user
      user.admin? ? admin_abilities : user_abilities(user)
    else
      guest_abilities
    end
  end

  def user_abilities(user)
    guest_abilities
    can :create, [Question, Answer, Comment]
    can :update, [Question, Answer], user_id: user.id
    # can :up, Vote
    # can :down, Vote
    # cannot :up, Vote, user_id: user.id
    # cannot :down, Vote, user_id: user.id
  end

  def guest_abilities
    can :tagged, Question
    can :read, :all
  end

  def admin_abilities
    can :manage, :all
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  has_many :comments, as: :commentable
  has_many :attachments, as: :attachmentable

  acts_as_votable

  accepts_nested_attributes_for :attachments, allow_destroy: true, reject_if: :all_blank

  validates :body, presence: true
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :user
  belongs_to :attachmentable, polymorphic: true

  mount_uploader :attachment, AttachmentUploader
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :commentable, polymorphic: true

  validates :body, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers
  has_many :comments, as: :commentable
  has_many :attachments, as: :attachmentable

  acts_as_taggable
  acts_as_votable
  is_impressionable

  accepts_nested_attributes_for :attachments, allow_destroy: true, reject_if: :all_blank

  validates :title, presence: true, uniqueness: true, length: {
      within: 10..40,
      too_short: 'Title must be more than 10 characters',
      too_long: 'Title cannot be more than 40 characters'
  }

  validates :body, presence: true, length: {
      within: 50..5000,
      too_short: 'Question must be more than 50 characters',
      too_long: 'Question cannot be more than 5000 characters'
  }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_merit

  has_many :questions
  has_many :answers
  has_many :comments

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true, length: {
      within: 2..20,
      too_short: 'Name must be more than 2 characters',
      too_long: 'Name cannot be more than 20 characters'
  }
end

app/controllers/answers_controller.rb
class AnswersController < InheritedResources::Base
  before_action :authenticate_user!, only: [:create, :edit]

  respond_to :js
  actions :create, :update, :edit

  belongs_to :question

  load_and_authorize_resource

  protected

  def create_resource(object)
    object.user = current_user
    object.attachments.each do |attachment|
      attachment.user = current_user
    end
    super
  end

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:id, :_destroy, :attachment])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :name) }
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :new]
  before_action :commentable_object, only: [:create, :new]

  load_and_authorize_resource

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @comment.commentable = @comment_object
    @comment.save
  end

  private

  def commentable_object
    @comment_object = Question.find(params[:question_id]) if params[:question_id]
    @comment_object = Answer.find(params[:answer_id]) if params[:answer_id]
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < InheritedResources::Base
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]
  before_action :build_answer, only: :show
  before_action :build_attachments, only: :new
  # before_action :question_belongs_to_current_user, only: [:edit, :update]
  impressionist actions: [:show], unique: [:session_hash]

  load_and_authorize_resource

  layout 'application', only: [:index, :edit, :new, :tagged]

  def tagged
    if params[:tag].present?
      @questions = Question.tagged_with(params[:tag])
    else
      redirect_to tags_path
    end
  end

  protected

  def create_resource(object)
    object.user = current_user
    object.attachments.each do |attachment|
      attachment.user = current_user
    end
    super
  end

  # TODO: switch to cancan.
  def question_belongs_to_current_user
    unless current_user == resource.user
      flash[:notice] = 'This is not your question.'
      redirect_to root_path
    end
  end

  def build_attachments
    build_resource.attachments.build
  end

  def build_answer
    @answer = resource.answers.build if user_signed_in?
    @answer.attachments.build if user_signed_in?
  end

  def question_params
    params.require(:question).permit(:tag_list, :title, :body, attachments_attributes: [:id, :_destroy, :attachment])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @search = ThinkingSphinx.search(params[:search])
  end

  private

  def search_params
    params.require(:search).permit(:search)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Question.tag_counts
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user!
  before_action :votable_object

  # load_and_authorize_resource

  def up
    @vote_object.vote_by voter: current_user, vote: true
    vote_response
  end

  def down
    @vote_object.vote_by voter: current_user, vote: false
    vote_response
  end

  private

  def vote_response
    render json: {vote_size: @vote_object.get_upvotes.size - @vote_object.get_downvotes.size}
  end

  def votable_object
    @vote_object = Question.find(params[:question_id]) if params[:question_id]
    @vote_object = Answer.find(params[:answer_id]) if params[:answer_id]
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
  def self.user
    @vote_object.user
  end
end

app/views/layouts/application.html.slim
doctype html
html
  =render 'shared/head'
  body
  =render 'shared/navbar'
  .container.content
    .row
      .col-md-8
        = yield
        = notice
        = alert
          .row
      .col-md-4
        =render 'shared/questions_sidebar'

app/views/layouts/questions.html.slim
doctype html
html
  =render 'shared/head'
  body
  =render 'shared/navbar'
  .container.content
    .row
      .col-md-8
        = yield
        = notice
        = alert
          .row
      .col-md-4
        =render 'shared/related_questions'

app/views/shared/_head.html.slim
head
  title
    | SoApp
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

app/views/shared/_navbar.html.slim
.navbar.navbar-default.navbar-static-top[role="navigation" ]
  .container
    .navbar-header
      a.navbar-brand Soapp
    .navbar-collapse.collapse
      ul.nav.navbar-nav
        li= link_to 'Questions', questions_path
        li= link_to 'Tags', tags_path
      .navbar-form.navbar-nav.nav
        = form_tag(search_index_path, method: :get) { text_field_tag('search', nil, placeholder: 'Search...', class: 'form-control') }
      ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          li.dropdown
            = link_to current_user.name, '#', class: 'dropdown-toggle', data: { toggle: 'dropdown' }
            ul.dropdown-menu
              li= link_to 'Profile', edit_user_registration_path
              li= link_to 'Logout', destroy_user_session_path, method: :delete
        - else
          li= link_to 'Sign in', new_user_session_path

app/views/shared/_questions_sidebar.html.slim
.row
  ul.nav.nav-list.nav-list-vivid
    li.nav-header Popular topics
    li
      a href="#fakelink"
        | Ruby on Rails
        span.badge.pull-right 255
    li.active
      a href="#fakelink"
        | Linux
        span.badge.pull-right 30
    li
      a href="#fakelink"
        | PHP
        span.badge.pull-right 4
    li.divider
    li.nav-header Most active users
    li
      a href="#fakelink"
        | Jon Snow
        span.badge.pull-right 69
    li
      a href="#fakelink"
        | Khaleesi
        span.badge.pull-right 21
    li
      a href="#fakelink"
        | Valar Morghulis
        span.badge.pull-right 40

app/views/shared/_related_questions.html.slim
.row
  ul.nav.nav-list.nav-list-vivid
    li.nav-header Related questions
    - for question in resource.find_related_tags do
      li = link_to question.title, question_path(question)