config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper
  devise_for :users

  concern :votable do
    post 'up' => 'votes#up'
    post 'down' => 'votes#down'
  end

  resources :questions do
    resources :answers, only: [:create, :edit, :update]
    resources :comments, only: [:new, :create]
    concerns :votable
  end

  resources :answers, only: [:edit, :update] do
    resources :comments, only: [:new, :create]
    concerns :votable
  end

  resources :tags, only: [:index]

  resources :search, only: [:index]

  root 'questions#index'
  get 'tagged' => 'questions#tagged', :as => 'tagged'

  namespace 'api', defaults: {format: 'json'} do
    namespace 'v1' do
      resource :profiles do
        get :me, on: :collection
        get :index, on: :collection
      end

      resources :questions, only: [:index, :show] do
      end
    end
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  has_many :comments, as: :commentable
  has_many :attachments, as: :attachmentable

  acts_as_votable

  accepts_nested_attributes_for :attachments, allow_destroy: true, reject_if: :all_blank

  validates :body, presence: true
end

app/controllers/answers_controller.rb
class AnswersController < InheritedResources::Base
  before_action :authenticate_user!, only: [:create, :edit]

  respond_to :js
  actions :create, :update, :edit

  belongs_to :question

  load_and_authorize_resource

  protected

  def create_resource(object)
    object.user = current_user
    object.attachments.each do |attachment|
      attachment.user = current_user
    end
    super
  end

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:id, :_destroy, :attachment])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answers.html.slim
ul.chat
  / TODO: WTF WITH THIS ARRAY?
  - for a in question.answers do
    - if a.persisted?
      .answer[id="answer_#{a.id}"]
        li.left-chat.clearfix
          span.chat-img.pull-left
            = gravatar_image_tag(a.user.email, alt: a.user.name, class: 'img-circle', size: 50, gravatar: { size: 50 })
            .vote
              .votecount = a.get_upvotes.size - a.get_downvotes.size
              = link_to 'Vote up', answer_up_path(a), remote: true, method: :post, class: 'up' if user_signed_in?
              = link_to 'Vote down', answer_down_path(a), remote: true, method: :post, class: 'down' if user_signed_in?
            - if current_user == a.user
              p.text-center
                = link_to 'Edit', edit_question_answer_path(question, a), remote: true
          .chat-body.clearfix
            .header
              strong.primary-font #{a.user.name} (#{a.user.points})
              small.pull-right.text-muted
                span.glyphicon.glyphicon-time
                | #{time_ago_in_words a.created_at} ago
            p.answer[id="answer#{a.id}"] = a.body
            ul.attachments[id="attachments#{a.id}"]
              = render 'answers/attachments', a: a
            ul.attachments
            .pull-right
              = link_to 'Comment answer', new_answer_comment_path(a), remote: true
        .comments*{data: {comment_id: a.id}}
          - if a.comments
            - for c in a.comments do
              li.right-chat.clearfix
                span.chat-img.pull-right
                  = gravatar_image_tag(c.user.email, alt: c.user.name, class: 'img-circle', size: 50, gravatar: { size: 50 })
                .chat-body.clearfix
                  .header
                    strong.pull-right.primary-font #{c.user.name}
                    small.text-muted
                      span.glyphicon.glyphicon-time
                      | #{time_ago_in_words c.created_at} ago
                  p = c.body
        .comment-form*{data: {comment_form_id: a.id}}

app/views/answers/_attachments.html.slim
- if a.attachments[0].respond_to?('attachment')
  - for attachment in a.attachments do
    - if attachment.attachment.file.respond_to?('filename')
      ul = link_to attachment.attachment.file.filename, attachment.attachment.url

app/views/answers/_edit_form.html.slim
= bootstrap_nested_form_for [parent, resource], remote: true do |f|
  = f.text_area :body, hide_label: true
  = f.fields_for :attachments, remote: true do |file|
    = link_to file.object.attachment.file.filename, file.object.attachment.url unless file.object.new_record?
    = file.file_field :attachment, hide_label: true if file.object.new_record?
    = file.link_to_remove ' - remove'
  = f.link_to_add 'add', :attachments
  br
  = f.primary 'Edit answer'

app/views/answers/create.js.erb
<% if @answer.errors.present? %>
<% @answer.errors.full_messages.each do |message| %>
$('.answer-errors').html('<%= j message %>');
<% end  %>
<% else %>
$('.answers').html('<%= j render 'answers/answers', question: parent %>');
$('#answer_body').val('');
<% end %>

app/views/answers/edit.js.erb
$('#answer<%= @answer.id %>').html('<%= j render 'answers/edit_form' %>');

app/views/answers/update.js.erb
$('#answer<%= @answer.id %>').html('<%= j @answer.body %>');
$('#attachments<%= @answer.id %>').html('');